### ISSUE TITLE
Confused calculating authorization header

### ISSUE THREAD

**Issue by upeuker** [ericmann/secure-xmlrpc#1]
Could you please clarify the creation of the Authorization string.

I have checked your sample and couldn't calculate the shown results in many cases (body without white spaces, body with linefeeds, body without linefeeds, ...).

In my real life test i got only error messages caused by wrong password or user name.

Thx

**Comment by ericmann** [comment]
Take a look at the actual hashing in the Authenticate function on line 215 if includes/XMLRPCS_Profile.php: https://github.com/ericmann/secure-xmlrpc/blob/master/includes/XMLRPCS_Profile.php#L215

```
$body = @file_get_contents('php://input');
$calculated = hash( 'sha256', $secret . $body );
```

**Comment by skreutzer** [comment]
The Base64 encoding of the SHA-256 hash is missing, I filed a pull request for it. You can manually fix it by changing the line mentioned above to

`$calculated = base64_encode(hash( 'sha256', $secret . $body ));`

Also make sure that `$_SERVER['HTTP_AUTHORIZATION']` is actually provided by your server configuration (I had to add `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` to my local WordPress .htaccess).

**Comment by ericmann** [comment]
No, nothing is missing. The documentation is pseudocode meant to illustrate the calculation. The `hash()` function _already_ does base64 encoding.
