### ISSUE TITLE
Configure HTTP Authorization header

### ISSUE THREAD

**Issue by skreutzer** [ericmann/secure-xmlrpc#3]
The problem still exists: If I send the HTTP header "Authorization: ..." on my machine, line 208 of $/includes/XMLRPCS_Profile.php says that $_SERVER['HTTP_AUTHORIZATION'] isn't set and will abort further plugin code execution. How to fix that for an Apache webserver in a secure way? Would a .htaccess on the root directory of the WordPress do it, containing the lines

```
RewriteEngine on
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

or would that too use a system environment variable to pass the authorization header on to PHP?

**Comment by ericmann** [comment]
The best I can do is point you at StackOverflow as this is an Apache issue, not an issue with this project in particular.

I found some details here: http://stackoverflow.com/a/17175260/326224. This may or may not be of some help to you.
